### ISSUE TITLE
[bug] 'jax.core' has no attribute 'thread_local_state' in 0.4.36 version of JAX

### ISSUE THREAD

**Issue by Routhleck** [chaobrain/brainstate#44]
https://github.com/chaobrain/brainstate/blob/bd2ca79bb247fcbb60fc74f300dd4665c657cd32/brainstate/util/_tracers.py#L28-L32
```
main = jax.core.thread_local_state.trace_state.trace_stack.stack[-1]
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
AttributeError: module 'jax.core' has no attribute 'thread_local_state'

**Comment by Routhleck** [comment]
I find the changlog said
> This release lands "stackless", an internal change to JAX's tracing machinery. We made trace dispatch purely a function of context rather than a function of both context and data. This let us delete a lot of machinery for managing data-dependent tracing: levels, sublevels, `post_process_call`, `new_base_main`, `custom_bind`, and so on. The change should only affect users that use JAX internals.
If you do use JAX internals then you may need to update your code (see https://github.com/jax-ml/jax/commit/c36e1f7c1ad4782060cbc8e8c596d85dfb83986f for clues about how to do this). There might also be version skew issues with JAX libraries that do this. If you find this change breaks your non-JAX-internals-using code then try the `config.jax_data_dependent_tracing_fallback` flag as a workaround, and if you need help updating your code then please file a bug.

https://github.com/jax-ml/jax/releases/tag/jax-v0.4.36

**Comment by chaoming0625** [comment]
A bad news.

**Comment by chaoming0625** [comment]
See #45
