### ISSUE TITLE
About the status of this package

### ISSUE THREAD

**Issue by PikaPei** [chaobrain/brainstate#47]
Hello!

I am a BrainPy user and recently saw the publication about brainunit. I then saw this package.
I'm curious if this package is ready to use for building SNN? Or can I implement anything from this book (https://brainpy.tech/book.html)?

Thank you!

**Comment by Routhleck** [comment]
Hi! Thank you for your interest in our work.

Brainunit and Brainstate have been basically developed, and we will continue to develop and maintain this [Brain Dynamics Programing Ecosystem](https://ecosystem-for-brain-dynamics.readthedocs.io/en/latest/) in the future.

We have completed many [examples](https://github.com/chaobrain/brainstate/tree/main/examples) and have bilingual [documents](https://brainstate.readthedocs.io/en/latest/) in Chinese and English.

As for the book, it is actually "outdated" (Regarding the code, most of it is from the old version of BrainPy, **but the textual aspects or conceptual parts remain consistent.**). If you want to implement using brainstate, I recommend you refer to our [documentation](https://brainstate.readthedocs.io/en/latest/).

**Comment by PikaPei** [comment]
Thank you for the explanation. I'll give it a try. It's really a wonderful work!
